version: '3'
services:
  postgresql:
    container_name: life_calendar_postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lifeCalendar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamadmin
  backend:
    container_name: backend
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - postgresql
  frontend:
    container_name: life_calendar_frontend
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  nginx:
    container_name: life_calendar_nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 3001:3001
      - 443:443
