version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lifeCalendar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamadmin
  backend:
    container_name: backend
    build: ./Backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443